CREATE TABLE IF NOT EXISTS Prompts (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(120) NOT NULL,
  Content TEXT NOT NULL,
  Tags VARCHAR(255),
  CreatedAt DATETIME NOT NULL,
  UpdatedAt DATETIME NULL
);
